[build]
  Command = "npm run build && npm run build:lambda"
  Functions = "lambda"
  Publish = "build"

[[redirects]]
  from = "https://triangles-slack.netlify.com/*"
  to = "https://triangles-slack.com/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
