[build]
  command = "yarn build"
  functions = "built-lambda"
  publish = "build"

[[redirects]]
  from = "https://triangles-slack.netlify.com/*"
  to = "https://triangles-slack.com/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
